// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3maFgqddM-Jfo1rf2CHKOE-q01dRU7E0',
    appId: '1:661395167065:web:fd786ed2eb4dbac0a69e48',
    messagingSenderId: '661395167065',
    projectId: 'flutter-web-28fae',
    authDomain: 'flutter-web-28fae.firebaseapp.com',
    storageBucket: 'flutter-web-28fae.appspot.com',
    measurementId: 'G-VZ3F34GDD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwUgUkUXaCY4rfYS4sZ0TVAAY8t7ziNeo',
    appId: '1:661395167065:android:4a4943e56bdb2194a69e48',
    messagingSenderId: '661395167065',
    projectId: 'flutter-web-28fae',
    storageBucket: 'flutter-web-28fae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARPYezuOZAVJqfn7D8H10G2vIiFm8_oVE',
    appId: '1:661395167065:ios:c7aef4c16aa35213a69e48',
    messagingSenderId: '661395167065',
    projectId: 'flutter-web-28fae',
    storageBucket: 'flutter-web-28fae.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARPYezuOZAVJqfn7D8H10G2vIiFm8_oVE',
    appId: '1:661395167065:ios:fcd1587b733640caa69e48',
    messagingSenderId: '661395167065',
    projectId: 'flutter-web-28fae',
    storageBucket: 'flutter-web-28fae.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
